version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.20
    steps:
      - checkout
      - run: go build .

  test:
    docker:
      - image: golang:1.20
    steps:
      - checkout
      - run: go test ./...

workflows:
  build_and_test:
    jobs:
     - build
     - test
